apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app-service: grafana 
{{ include "common-resources.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: grafana
    release: {{ .Release.Name }}
