image-name="ggrig/jmeter-c-icap:2.3"

build:
	docker build -t $(image-name) .

run:
	docker run -d $(image-name)

tag:
	docker tag ggrig/jmeter-c-icap ggrig/jmeter-c-icap:2.3

push:
	docker push ggrig/jmeter-c-icap:2.3
