apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minio
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"  
      containers:
      - name: minio
        image: minio/minio:RELEASE.2020-10-09T22-55-05Z
        args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key : "MINIO_ACCESS_KEY"
              name: "minio-creds"
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key : "MINIO_SECRET_KEY"
              name: "minio-creds"
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
          - name: minio-storage
            mountPath: /data
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-storage
---
apiVersion: v1
kind: Service
metadata:
  namespace: minio
  name: minio
  labels:
    service: minio
spec:
  selector:
    app: minio
  ports:
    - name: http
      port:  9000
  type: ClusterIP      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: minio
  name: minio-storage
spec:
  storageClassName: azure-file-storage
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "100Gi"
---
apiVersion: autoscaling/v2beta1 
kind: HorizontalPodAutoscaler 
metadata: 
  name: minio
  namespace: minio
  labels:
    app: minio
spec: 
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: minio
  metrics: 
  - type: Resource 
    resource: 
      name: cpu 
      targetAverageUtilization: 75
  - type: Resource 
    resource: 
      name: memory 
      targetAverageUtilization: 75
